### PR TITLE
Persist selected plan on browser refresh

### LINKED ISSUE #697: RVL-878 - Selected plan should persist after refreshing 'Update Plan' page
When a user refreshes the Update Plan page for an existing plan (e.g. pressing control-R) the page reloads with no information. Note that the urls are the same , and that if the plan is saved, it overwrites the original plan

To reproduce:

1. Navigate to  Manage Plans
2. Click on a Plan
3. Click control-R when on the Update Plan page

As reported here https://smartregister.atlassian.net/browse/RVL-878

### PR DESCRIPTION
**Pull request by ciremusyoka**
Closes #697

### CODE REVIEW

File: src/containers/pages/InterventionPlan/UpdatePlan/index.tsx [hunk 1]
```diff
@@ -43,13 +43,15 @@ const UpdatePlan = (props: RouteComponentProps<RouteParams> & UpdatePlanProps) =
...
+  const apiService = new service(OPENSRP_PLANS);
 
   /** async function to load the data */
   async function loadData() {
     try {
       setLoading(plan === null); // only set loading when there are no plans
       const planFromAPI = await apiService.read(planIdentifier);
-      fetchPlan(planFromAPI);
+      const currentPlan = Array.isArray(planFromAPI) ? planFromAPI[0] : planFromAPI;
+      fetchPlan(currentPlan);
```
Comment (ciremusyoka) [inline src/containers/pages/InterventionPlan/UpdatePlan/index.tsx]: The data we are getting from API is a `list` but we were using it as an `object` thus when filtering using the `planIdentifier` it could not be found.

File: src/containers/pages/InterventionPlan/UpdatePlan/index.tsx [hunk 2]
```diff
@@ -43,13 +43,15 @@ const UpdatePlan = (props: RouteComponentProps<RouteParams> & UpdatePlanProps) =
   if (!planIdentifier) {
     return null; /** we should make this into a better error page */
   }
+  const apiService = new service(OPENSRP_PLANS);
```
Comment (ciremusyoka) [inline src/containers/pages/InterventionPlan/UpdatePlan/index.tsx]: Also with the `apiService` defined before being called  was causing a problem which have not yet been able to understand fully.

Comment (moshthepitt) [reply src/containers/pages/InterventionPlan/UpdatePlan/index.tsx]: This probably came from the more aggressive linter that we are now using.

**Comment by moshthepitt** [comment]
Created a related issue to get this fixed API-side https://github.com/OpenSRP/opensrp-server-web/issues/213

**Comment by ciremusyoka** [comment]
> @ciremusyoka nice catch, well done. 
> 
> Please add a test for this. In my view, tests are especially important for bugfixes so that we avoid regressions.

@moshthepitt I think the test for this case should be covered on `Server side` to ensure consistency of data type being returned. To test the data type, i will be using a set of predefined mock data but if the `Server`  keeps on returning different data types our tests will not be able handle that. They will pass but still the bug will be there.

**Comment by moshthepitt** [comment]
@ciremusyoka while what you are saying makes sense, from the point of view of our code we still need a const currentPlan = Array.isArray(planFromAPI) ? planFromAPI[0] : planFromAPI;
      fetchPlan(currentPlan);test to ensure that our fix is in place and works.  i.e.

```ts
const currentPlan = Array.isArray(planFromAPI) ? planFromAPI[0] : planFromAPI;
fetchPlan(currentPlan);
```

^^ this should be testable, right?

**Comment by ciremusyoka** [comment]
> @ciremusyoka while what you are saying makes sense, from the point of view of our code we still need a const currentPlan = Array.isArray(planFromAPI) ? planFromAPI[0] : planFromAPI;
> fetchPlan(currentPlan);test to ensure that our fix is in place and works. i.e.
> 
> ```ts
> const currentPlan = Array.isArray(planFromAPI) ? planFromAPI[0] : planFromAPI;
> fetchPlan(currentPlan);
> ```
> 
> ^^ this should be testable, right?

@moshthepitt Yes it does.

**Comment by moshthepitt** [comment]
@ciremusyoka cool, lets add the test so that we can merge and close this.
