### PR TITLE
Fix revoke assignments bug

### LINKED ISSUE #1690: Assign End Pointing Unable to Revoke Team Assignment
The /assign end point on Thailand Production is failing to revoke team assignment. See the conversation and video [here](https://dsme.slack.com/archives/C0194A6JV35/p1646720689554969). See the sample for removing team `PHO_KBI` on the [this](https://mhealth.ddc.moph.go.th/assign/9faddd53-de98-48e2-8f2c-b72bda835f3a/a0b4609f-5589-4e7f-b432-4a78e4c366f5) link.

### PR DESCRIPTION
**Pull request by ciremusyoka**
Fixes #1690 

Updates `endDate` of revoked team assignments to current date.

### CODE REVIEW

**Review by KipSigei — APPROVED** [review]

File: src/containers/pages/PlanAssignment/helpers/JurisdictionAssignmentForm/helpers.ts [hunk 1]
```diff
@@ -55,7 +55,7 @@ export const getPayload = (
   }
 
   // turns out if you put it in the loop it keeps subtracting a day for every iteration
-  const retireDate = now.format();
+  const retireDate = moment(new Date()).format();
```
Comment (p-netm) [inline src/containers/pages/PlanAssignment/helpers/JurisdictionAssignmentForm/helpers.ts:58]: @ciremusyoka isn't `now === moment(new Date())`. ama whats the change?

**Review by machariamuguku — APPROVED** [review]

File: src/containers/pages/PlanAssignment/helpers/JurisdictionAssignmentForm/helpers.ts (hunk 1 above)
Comment (ciremusyoka) [reply src/containers/pages/PlanAssignment/helpers/JurisdictionAssignmentForm/helpers.ts:58]: @p-netm [this](https://github.com/onaio/reveal-frontend/blob/4c4413d9a3a92b3dfc2f1e21274ed2f708dd3b59/src/containers/pages/PlanAssignment/helpers/JurisdictionAssignmentForm/helpers.ts#L31-L33) part is updating `now` date object that why am redefining it.

Comment (p-netm) [reply src/containers/pages/PlanAssignment/helpers/JurisdictionAssignmentForm/helpers.ts:58]: cool
