### PR TITLE
Assign page fix

### LINKED ISSUE #556: Issues on assign page
assignment

- [x] The page says `IRS` when it should not
- [x] The breadcrumbs dont let you go back
- [x] The <title> tag on this page says `IRS: ,A1 - Ban Huai Haeng OA - 2019-10-22`

### PR DESCRIPTION
**Pull request by p-netm**
Includes fixes for the assign Page as proposed in #556 closes #556 
Changes:
- Refactors so that displayed text on pages tiltles and document titles align with the page's purposes
- Refactor so that one can now drill up in the `drilldown` by clicking the `tableCrumbs`

### CODE REVIEW

**Comment by moshthepitt** [comment]
@p-netm confirmed that the breadcrumb assign jursidiction links work?

File: src/containers/pages/IRS/assignments/index.tsx [hunk 1]
```diff
@@ -46,7 +47,7 @@ const IRSAssignmentPlansList = (props: PlanAssignmentsListProps) => {
   const { fetchPlans, plans } = props;
   const [loading, setLoading] = useState<boolean>(plans.length < 1);
 
-  const pageTitle: string = IRS_PLANS;
+  const pageTitle: string = `${ASSIGN_PLANS}`;
```
Comment (cKellyDesign) [inline src/containers/pages/IRS/assignments/index.tsx]: oops, good catch

File: src/containers/pages/InterventionPlan/IRS/plan/index.tsx [hunk 2]
```diff
@@ -503,16 +508,9 @@ class IrsPlan extends React.Component<
...
-          </Col>
-        )}
-        {!isFinalizedPlan && (
-          <Col xs="8" className="page-title-col">
-            <h2 className="page-title">IRS: {pageLabel}</h2>
-          </Col>
-        )}
+        <Col xs="8" className="page-title-col">
+          <h2 className="page-title">{displayedPageLabel}</h2>
+        </Col>
```
Comment (cKellyDesign) [inline src/containers/pages/InterventionPlan/IRS/plan/index.tsx]: Excellent!

**Comment by cKellyDesign** [comment]
> confirmed that the breadcrumb assign jursidiction links work?

@moshthepitt i've confirmed that the page level and drilldown level breadcrumbs work in both planning and assignment views.
