### PR TITLE
1149 fix map drill down on team assignment page

### LINKED ISSUE #1149: Navigation via the map is broken on Team Assignment page
It seems that the map component is generating an invalid url when one clicks on the map (when trying to drill down jurisdictions).

### PR DESCRIPTION
**Pull request by KipSigei**
Fixes #1149

### CODE REVIEW

File: src/containers/pages/AssigmentMapWrapper/helpers/utils.tsx [hunk 1]
```diff
@@ -35,12 +31,8 @@ export const onJurisdictionClick = (
       deselectNodeCreator,
       currentChildren,
       plan,
-      autoSelectionFlow,
+      baseAssignmentURL,
     } = props;
-
-    const baseUrl = !autoSelectionFlow
-      ? `${MANUAL_ASSIGN_JURISDICTIONS_URL}/${plan.identifier}/${rootJurisdictionId}`
-      : `${AUTO_ASSIGN_JURISDICTIONS_URL}/${plan.identifier}/${rootJurisdictionId}`;
```
Comment (p-netm) [inline src/containers/pages/AssigmentMapWrapper/helpers/utils.tsx:43]: @KipSigei would this then mean we do not need the `autoSelectionFlow` prop any more for this component.

Comment (KipSigei) [reply src/containers/pages/AssigmentMapWrapper/helpers/utils.tsx:43]: addressed https://github.com/onaio/reveal-frontend/pull/1161/commits/186a75e03be2bc2d8564ff1ec64b9f041f0fea44
