### PR TITLE
Fix endless loading on irs map

### LINKED ISSUE #1451: IRS map loads forever when Superset error is encountered
e.g. https://web.reveal-zm.smartregister.org/intervention/irs/report/4cbe10b9-231e-5084-9646-0a923dcfa0da/04f4a5b9-31a5-48e9-bcd0-c389be95c35d/map

### PR DESCRIPTION
**Pull request by ciremusyoka**
This pr fixes endless loading on the map component when there is an error on the points to be loaded. In case of an error the error page will be loaded.

Fixes #1451

### CODE REVIEW

**Review by moshthepitt — CHANGES_REQUESTED** [review]
Could we ensure, by way of a test, that the map will load if the IRS jurisdiction is present but the IRS structures are missing or their request to Superset errors out?

File: src/components/GisidaLite/helpers.tsx [hunk 1]
```diff
@@ -90,3 +94,34 @@ export const gsLiteStyle: Style | string = DIGITAL_GLOBE_CONNECT_ID
...
+  let zoom;
+  if (structures?.features?.length) {
+    mapBounds = GeojsonExtent(structures);
+  }
+  if (!mapBounds && jurisdiction?.geojson) {
+    mapBounds = GeojsonExtent(jurisdiction.geojson);
+  }
+  // get map zoom and center values
+  if (mapBounds) {
+    const centerAndZoom = viewport(mapBounds, [600, 400]);
```
Comment (moshthepitt) [inline src/components/GisidaLite/helpers.tsx:118]: could we make these magic numbers params in the function? Thinking of this from an [open/closed](https://stackify.com/solid-design-open-closed-principle/) perspective.

File: src/components/GisidaLite/helpers.tsx [hunk 2]
```diff
@@ -90,3 +94,34 @@ export const gsLiteStyle: Style | string = DIGITAL_GLOBE_CONNECT_ID
...
+) => {
+  let mapCenter;
+  let mapBounds;
+  let zoom;
+  if (structures?.features?.length) {
+    mapBounds = GeojsonExtent(structures);
+  }
+  if (!mapBounds && jurisdiction?.geojson) {
+    mapBounds = GeojsonExtent(jurisdiction.geojson);
+  }
```
Comment (moshthepitt) [inline src/components/GisidaLite/helpers.tsx:115]: This means that if both the jurisdiction and the structures are defined then we will use the jurisdiction to get the center and zoom.  Could we make it the other way round (which is how it is currently).  i.e. that the structures will override the jurisdiction if both exist

File: src/components/GisidaLite/helpers.tsx [hunk 3]
```diff
@@ -90,3 +94,34 @@ export const gsLiteStyle: Style | string = DIGITAL_GLOBE_CONNECT_ID
...
+  // get map zoom and center values
+  if (mapBounds) {
+    const centerAndZoom = viewport(mapBounds, [600, 400]);
+    mapCenter = centerAndZoom.center;
+    zoom = centerAndZoom.zoom;
+  }
+  return {
```
Comment (moshthepitt) [inline src/components/GisidaLite/helpers.tsx:122]: what will you return if you have neither structures nor a jurisdiction?  should we make the jurisdiction mandatory for this function?

**Review by moshthepitt — CHANGES_REQUESTED** [review]

File: src/components/GisidaLite/helpers.tsx (hunk 2 above)
Comment (ciremusyoka) [reply src/components/GisidaLite/helpers.tsx:115]: we will only use jurisdiction if structures are not defined. That is why on line 113 am first checking if `mapBounds`  is defined.

File: src/components/GisidaLite/helpers.tsx (hunk 3 above)
Comment (ciremusyoka) [reply src/components/GisidaLite/helpers.tsx:122]: When we have no structures or jurisdiction all those value will be returned as undefined. 
Because we are using jurisdiction geojson which is optional to generate the map bounds even if we make jurisdiction mandatory and geojson isn't we will have same results.

**Review by moshthepitt — APPROVED** [review]

**Review by kelvin-muchiri — APPROVED** [review]
